<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="rmomin-PC" name="hello.NewTest2" tests="1" failures="0" timestamp="20 Jan 2016 06:06:41 GMT" time="0.011" errors="1">
  <testcase name="f" time="0.011" classname="hello.NewTest2">
    <error type="java.lang.Error" message="Unresolved compilation problems: 
	OLDEST_FIRST cannot be resolved or is not a field
	Type mismatch: cannot convert from void to ExtentTest
	The method endTest() in the type ExtentReports is not applicable for the arguments (ExtentTest)
	The method flush() is undefined for the type ExtentReports
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
	OLDEST_FIRST cannot be resolved or is not a field
	Type mismatch: cannot convert from void to ExtentTest
	The method endTest() in the type ExtentReports is not applicable for the arguments (ExtentTest)
	The method flush() is undefined for the type ExtentReports

	at hello.NewTest2.f(NewTest2.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- f -->
</testsuite> <!-- hello.NewTest2 -->
